CROP_SET_CONFIGS = {
    "memory": {
        "output_file":                    "mem_to_t1_train_crop.json",
        "probs_file":                     "p_true_to_ft1_train_crop.json",
        "probs_source_subdir":            "train",
        "invert_prob":                    False,
        "probs_skip_msg":                 "Skipping GT probabilities computation for FT1 train crops: it has been already done!",
        "probs_start_msg":                "Computing GT probabilities for FT1 train crops...",
        "xai_agg_scores_file":            "greeness_to_ft1_train_crop.json",
        "xai_agg_scores_coords_file":     "coords_to_ft1_train_crop.json",
        "xai_agg_scores_score_sign":      1,
        "xai_agg_scores_tqdm_desc":       "Processing FT1 train pages",
        "xai_agg_scores_skip_msg":        "Skipping greeness computation for FT1 train crops: it has been already done!",
        "xai_agg_scores_start_msg":       "Computing greeness for FT1 train crops...",
        "skip_msg":                       "Skipping memory scores computation for FT1 train crops: it has been already done!",
        "start_msg":                      "Computing memory scores for FT1 train crops...",
        "tqdm_desc":                      "Computing memory scores for FT1 train crops",
        "extract_tqdm_desc":              "Extracting FT1 train crops",
    },
    "openness": {
        "output_file":                    "openness_to_xai_crop.json",
        "probs_file":                     "p_error_to_xai_crop.json",
        "probs_source_subdir":            "xai_crops",
        "invert_prob":                    True,
        "probs_skip_msg":                 "Skipping error probabilities computation for XAI-guided crops: it has been already done!",
        "probs_start_msg":                "Computing error probabilities for XAI-guided crops...",
        "xai_agg_scores_file":            "redness_to_xai_crop.json",
        "xai_agg_scores_coords_file":     "coords_to_xai_crop.json",
        "xai_agg_scores_score_sign":      -1,
        "xai_agg_scores_tqdm_desc":       "Processing XAI-guided crops",
        "xai_agg_scores_skip_msg":        "Skipping redness computation for XAI-guided crops: it has been already done!",
        "xai_agg_scores_start_msg":       "Computing redness for XAI-guided crops...",
        "skip_msg":                       "Skipping openness scores computation for XAI-guided crops: it has been already done!",
        "start_msg":                      "Computing openness scores for XAI-guided crops...",
        "tqdm_desc":                      "Computing openness scores for XAI-guided crops",
        "extract_tqdm_desc":              "Extracting XAI-guided crops",
    },
}

__all__ = [CROP_SET_CONFIGS]